using System.Text;
using System.Text.Json;
using NodalMerge.Studio.Storage;
using NodalMerge.Studio.Storage.TreeObjects;

namespace NodalMerge.Studio.Integration.Tests;

/// <summary>
/// docs/TREE_OBJECT_FORMAT.md — pins CanonicalTreeSerializer to the frozen golden vectors in
/// TestData/tree-format-vectors.v1.json (generated by an independent implementation of the format
/// doc's rules). Any byte drift here is a format break, not a refactor.
/// </summary>
[Trait("Category", "Integration")]
public class CanonicalTreeSerializerVectorTests
{
    // xunit [Theory] parameter types must be at least as accessible as the test method itself.
    public sealed record V1Vector(
        string Id, IReadOnlyDictionary<string, string> InputEntries, byte[] ExpectedBytes, string ExpectedHash);

    public sealed record V2Blob(string Directory, byte[] ExpectedBytes, string ExpectedHash);

    public sealed record V2Vector(
        string Id, IReadOnlyDictionary<string, string> InputEntries, IReadOnlyList<V2Blob> ExpectedBlobs, string ExpectedRootHash);

    private static readonly string VectorsPath =
        Path.Combine(AppContext.BaseDirectory, "TestData", "tree-format-vectors.v1.json");

    private static (IReadOnlyList<V1Vector> V1, IReadOnlyList<V2Vector> V2) LoadVectors()
    {
        using var doc = JsonDocument.Parse(File.ReadAllBytes(VectorsPath));
        var v1 = new List<V1Vector>();
        var v2 = new List<V2Vector>();

        foreach (var vector in doc.RootElement.GetProperty("vectors").EnumerateArray())
        {
            var id = vector.GetProperty("id").GetString()!;
            var kind = vector.GetProperty("kind").GetString();
            var inputEntries = vector.GetProperty("input_entries").EnumerateObject()
                .ToDictionary(p => p.Name, p => p.Value.GetString()!, StringComparer.Ordinal);

            if (kind == "v1")
            {
                var expectedBytes = Encoding.UTF8.GetBytes(vector.GetProperty("expected_bytes").GetString()!);
                var expectedHash = vector.GetProperty("expected_hash").GetString()!;
                v1.Add(new V1Vector(id, inputEntries, expectedBytes, expectedHash));
            }
            else if (kind == "v2")
            {
                var blobs = vector.GetProperty("expected_blobs").EnumerateArray()
                    .Select(b => new V2Blob(
                        b.GetProperty("directory").GetString()!,
                        Encoding.UTF8.GetBytes(b.GetProperty("expected_bytes").GetString()!),
                        b.GetProperty("expected_hash").GetString()!))
                    .ToList();
                var rootHash = vector.GetProperty("expected_root_hash").GetString()!;
                v2.Add(new V2Vector(id, inputEntries, blobs, rootHash));
            }
        }

        return (v1, v2);
    }

    public static IEnumerable<object[]> V1VectorData() => LoadVectors().V1.Select(v => new object[] { v });

    public static IEnumerable<object[]> V2VectorData() => LoadVectors().V2.Select(v => new object[] { v });

    [Theory]
    [MemberData(nameof(V1VectorData))]
    public void SerializeFlat_matches_the_golden_vector_bytes_and_hash(V1Vector vector)
    {
        var bytes = CanonicalTreeSerializer.SerializeFlat(vector.InputEntries);

        Assert.Equal(vector.ExpectedBytes, bytes);
        Assert.Equal(vector.ExpectedHash, BlobHasher.ComputeHash(bytes));
    }

    [Theory]
    [MemberData(nameof(V1VectorData))]
    public void SerializeFlat_is_deterministic_regardless_of_call_count_or_insertion_order(V1Vector vector)
    {
        var first = CanonicalTreeSerializer.SerializeFlat(vector.InputEntries);
        var second = CanonicalTreeSerializer.SerializeFlat(vector.InputEntries);
        Assert.Equal(first, second);

        // Rebuild the same entries in reverse insertion order — sort key is the path, not
        // insertion order, so the output must still be byte-identical.
        var reordered = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var kv in vector.InputEntries.Reverse())
            reordered[kv.Key] = kv.Value;

        var thirdBytes = CanonicalTreeSerializer.SerializeFlat(reordered);
        Assert.Equal(first, thirdBytes);
    }

    [Theory]
    [MemberData(nameof(V1VectorData))]
    public void Parse_v1_vector_bytes_round_trips_the_flat_entries(V1Vector vector)
    {
        var doc = CanonicalTreeSerializer.Parse(vector.ExpectedBytes);

        Assert.Equal(1, doc.Version);
        Assert.NotNull(doc.FlatEntries);
        Assert.Null(doc.Entries);
        Assert.Equal(
            vector.InputEntries.OrderBy(kv => kv.Key, StringComparer.Ordinal),
            doc.FlatEntries!.OrderBy(kv => kv.Key, StringComparer.Ordinal));
    }

    [Theory]
    [MemberData(nameof(V2VectorData))]
    public void Parse_v2_blob_bytes_round_trips_the_entry_list_and_hashes_match(V2Vector vector)
    {
        foreach (var blob in vector.ExpectedBlobs)
        {
            var doc = CanonicalTreeSerializer.Parse(blob.ExpectedBytes);
            Assert.Equal(2, doc.Version);
            Assert.Null(doc.FlatEntries);
            Assert.NotNull(doc.Entries);

            // Independently re-parse the raw entries array (not via CanonicalTreeSerializer) so this
            // isn't just checking the production parser against itself.
            using var raw = JsonDocument.Parse(blob.ExpectedBytes);
            var rawEntries = raw.RootElement.GetProperty("entries").EnumerateArray().ToList();

            Assert.Equal(rawEntries.Count, doc.Entries!.Count);
            for (var i = 0; i < rawEntries.Count; i++)
            {
                Assert.Equal(rawEntries[i].GetProperty("n").GetString(), doc.Entries[i].Name);
                Assert.Equal(rawEntries[i].GetProperty("h").GetString(), doc.Entries[i].Hash);
                var expectedKind = rawEntries[i].GetProperty("k").GetString() == "f"
                    ? TreeEntryKind.File
                    : TreeEntryKind.Directory;
                Assert.Equal(expectedKind, doc.Entries[i].Kind);
            }

            // Sanity check that BlobHasher (BLAKE3) agrees with the vector's independently
            // computed hash for these exact bytes.
            Assert.Equal(blob.ExpectedHash, BlobHasher.ComputeHash(blob.ExpectedBytes));
        }
    }

    [Fact]
    public void Parse_throws_FormatException_for_a_non_tree_payload()
    {
        var bytes = Encoding.UTF8.GetBytes("{\"foo\":\"bar\"}");
        Assert.Throws<FormatException>(() => CanonicalTreeSerializer.Parse(bytes));
    }

    [Fact]
    public void Parse_throws_FormatException_for_an_unsupported_version()
    {
        var bytes = Encoding.UTF8.GetBytes("{\"nodalmerge\":\"tree\",\"version\":99,\"entries\":{}}");
        Assert.Throws<FormatException>(() => CanonicalTreeSerializer.Parse(bytes));
    }
}
